service: mongodb-service
provider:
  name: aws
  runtime: nodejs16.x
  region: ap-northeast-2

functions:
  getUserData:
    handler: getUserData.handler
  postUserData:
    handler: postUserData.handler
